import React, { useLayoutEffect, useMemo, useRef, useState } from "react";
import { SectionHeading, toHexColors } from "./AnatomySpec";
import { paletteName } from "./AnatomyColors";
import { usePreviewMode } from "./PreviewModeContext";
import COLORS from "./componentColors.generated.json";

/** One colour declaration from components.css — generated by
 *  scripts/generate-component-colors.mjs (runs with `npm run dev`). */
type ColorRef = { variant: string; state: string; part: string; property: string; token: string; mode: "both" | "dark"; mix: boolean };
type Resolved = { hex: string; name?: string };

const DATA = COLORS as Record<string, ColorRef[]>;

/** Resolves every token to its hex in light and dark by probing an element
 *  under each mode scope, so the table always matches the live palette. */
function resolveTokens(tokens: string[]): Record<"light" | "dark", Record<string, Resolved>> {
  const out = { light: {}, dark: {} } as Record<"light" | "dark", Record<string, Resolved>>;
  for (const m of ["light", "dark"] as const) {
    const host = document.createElement("div");
    host.dataset.theme = "core";
    host.dataset.mode = m;
    host.style.cssText = "position:absolute;visibility:hidden;pointer-events:none";
    document.body.appendChild(host);
    for (const t of tokens) {
      const probe = document.createElement("i");
      probe.style.color = `var(--${t})`;
      host.appendChild(probe);
      const hex = toHexColors(getComputedStyle(probe).color).toUpperCase();
      out[m][t] = { hex, name: paletteName(hex, t) };
    }
    host.remove();
  }
  return out;
}

const cell: React.CSSProperties = { padding: "var(--core-space-2) var(--core-space-4)", borderTop: "1px solid var(--neutral-border-light)", verticalAlign: "middle" };
const head: React.CSSProperties = { padding: "var(--core-space-2) var(--core-space-4)", fontWeight: 700 };

function Swatch({ value, onCopy, copied }: { value?: Resolved; onCopy: (hex: string) => void; copied: boolean }) {
  if (!value) return <span style={{ color: "var(--neutral-text-subtle-light)" }}>—</span>;
  return (
    <button
      type="button"
      onClick={() => onCopy(value.hex)}
      title={`Copy ${value.hex}`}
      style={{ display: "inline-flex", alignItems: "center", gap: 8, background: "none", border: 0, padding: 0, cursor: "pointer", color: "inherit", font: "inherit", textAlign: "left" }}
    >
      <span style={{ width: 16, height: 16, borderRadius: 4, flex: "none", background: value.hex, boxShadow: "inset 0 0 0 1px var(--neutral-border-light)" }} />
      <span>
        <span style={{ fontWeight: 600, color: "var(--neutral-text-default)" }}>{copied ? "Copied" : value.name ?? "—"}</span>{" "}
        <span style={{ fontFamily: "var(--typography-font-family-mono, monospace)", color: "var(--neutral-text-subtle)" }}>{value.hex}</span>
      </span>
    </button>
  );
}

/** "All colors" reference for a component's anatomy: every variant and state
 *  the stylesheet paints, with its design-system token and light/dark value.
 *  Finds its component from the nearest ancestor section id (like AutoSizing). */
export function ComponentColorReference() {
  const ref = useRef<HTMLDivElement>(null);
  const [key, setKey] = useState<string | null>(null);
  const [variant, setVariant] = useState("All");
  const [copied, setCopied] = useState<string | null>(null);
  const { mode } = usePreviewMode();

  useLayoutEffect(() => {
    for (let el: HTMLElement | null = ref.current; el; el = el.parentElement) {
      if (el.id && DATA[el.id]?.length) return setKey(el.id);
    }
  }, []);

  const rows = key ? DATA[key] : [];
  const variants = useMemo(() => [...new Set(rows.map((r) => r.variant))], [rows]);
  const resolved = useMemo(() => (rows.length ? resolveTokens([...new Set(rows.map((r) => r.token))]) : null), [rows, mode]);

  const copy = (id: string, text: string) => {
    navigator.clipboard?.writeText(text).catch(() => {});
    setCopied(id);
    window.setTimeout(() => setCopied((c) => (c === id ? null : c)), 1500);
  };

  if (!key || !resolved) return <div ref={ref} />;
  const shown = variants.filter((v) => variant === "All" || v === variant);

  return (
    <div ref={ref} style={{ marginTop: 40 }}>
      <SectionHeading>All colors — every variant & state ({rows.length})</SectionHeading>
      {variants.length > 1 && (
        <div role="group" aria-label="Filter by variant" style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 16 }}>
          {["All", ...variants].map((v) => (
            <button
              key={v}
              type="button"
              aria-pressed={variant === v}
              onClick={() => setVariant(v)}
              style={{
                padding: "var(--core-space-1) var(--core-space-3)",
                borderRadius: 999,
                border: "1px solid var(--neutral-border-light)",
                background: variant === v ? "var(--brand-background-primary-subtle)" : "var(--neutral-surface-layer-01)",
                color: variant === v ? "var(--brand-text-primary-default)" : "var(--neutral-text-subtle)",
                fontSize: "var(--typography-body-sm-size)",
                fontWeight: 600,
                cursor: "pointer",
              }}
            >
              {v}
            </button>
          ))}
        </div>
      )}
      <div className="docs-spec-card" style={{ border: "1px solid var(--neutral-border-light)", borderRadius: 12, overflowX: "auto", background: "var(--neutral-surface-layer-01)" }}>
        <table style={{ borderCollapse: "collapse", fontSize: "var(--typography-body-sm-size)", width: "100%", minWidth: 900 }}>
          <thead>
            <tr style={{ textAlign: "left", color: "var(--neutral-text-subtle)", fontSize: 11, textTransform: "uppercase", letterSpacing: "0.06em", background: "var(--neutral-surface-layer-03)" }}>
              <th style={head}>State</th>
              <th style={head}>Part</th>
              <th style={head}>Property</th>
              <th style={head}>Token</th>
              <th style={head}>Light</th>
              <th style={head}>Dark</th>
            </tr>
          </thead>
          <tbody>
            {shown.map((v) => (
              <React.Fragment key={v}>
                {variants.length > 1 && (
                  <tr>
                    <td colSpan={6} style={{ ...cell, fontWeight: 700, color: "var(--neutral-text-default)", background: "var(--neutral-background)" }}>
                      {v === "Base" ? "Base (all variants)" : v}
                    </td>
                  </tr>
                )}
                {rows.filter((r) => r.variant === v).map((r, i) => {
                  const id = `${v}-${i}`;
                  return (
                    <tr key={id}>
                      <td style={{ ...cell, color: "var(--neutral-text-default)" }}>
                        {r.state}
                        {r.mode === "dark" && <span style={{ marginLeft: 6, fontSize: 11, padding: "0 6px", borderRadius: 4, background: "var(--brand-background-primary-subtle)", color: "var(--brand-text-primary-default)" }}>Dark only</span>}
                      </td>
                      <td style={{ ...cell, color: "var(--neutral-text-subtle)" }}>{r.part}</td>
                      <td style={{ ...cell, color: "var(--neutral-text-subtle)", fontFamily: "var(--typography-font-family-mono, monospace)" }}>{r.property}</td>
                      <td style={{ ...cell, fontFamily: "var(--typography-font-family-mono, monospace)" }}>
                        <button type="button" title="Copy token" onClick={() => copy(`${id}-t`, `var(--${r.token})`)} style={{ background: "none", border: 0, padding: 0, cursor: "pointer", color: "var(--neutral-text-default)", font: "inherit" }}>
                          {copied === `${id}-t` ? "Copied" : r.token}
                        </button>
                        {r.mix && <span title="Blended with color-mix()" style={{ marginLeft: 6, fontSize: 11, color: "var(--neutral-text-subtle)" }}>mix</span>}
                      </td>
                      <td style={cell}>{r.mode === "dark" ? <span style={{ color: "var(--neutral-text-subtle-light)" }}>—</span> : <Swatch value={resolved.light[r.token]} copied={copied === `${id}-l`} onCopy={(h) => copy(`${id}-l`, h)} />}</td>
                      <td style={cell}><Swatch value={resolved.dark[r.token]} copied={copied === `${id}-d`} onCopy={(h) => copy(`${id}-d`, h)} /></td>
                    </tr>
                  );
                })}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
